id: carrefour
name: "Carrefour"
description: "Carrefour Loyalty Card"
country: EU
category: groceries
barcode_type: ean13
brand:
  logo: siCarrefour
  primary_color: "#004C97"
  secondary_color: "#ED1C24"
  text_color: "#FFFFFF"
