id: decathlon-fr
name: Décathlon
description: Décathlon Card
country: FR
domain: decathlon.fr
category: sports
barcode_type: ean13
brand:
  logo: siDecathlon
  primary_color: "#0082C3"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
apps:
  android:
    package: com.decathlon.app
