id: dm-cz
name: dm drogerie
description: dm active beauty Card
country: CZ
domain: dm-drogeriemarkt.cz
category: pharmacy
barcode_type: ean13
brand:
  logo: siDm
  primary_color: "#FFD700"
  secondary_color: "#FFFFFF"
  text_color: "#000000"
apps:
  ios:
    store_id: "1440180301"
