id: dm-de
name: "dm"
description: "dm Payback Card"
country: DE
category: pharmacy
barcode_type: ean13
brand:
  logo: siDm
  primary_color: "#FFD700"
  secondary_color: "#FFFFFF"
  text_color: "#000000"
