id: dm-hr
name: "dm"
description: "dm active beauty Card"
country: HR
domain: "dm.hr"
category: pharmacy
barcode_type: ean13
brand:
  logo: siDm
  primary_color: "#FFD700"
  secondary_color: "#FFFFFF"
  text_color: "#000000"
