id: dm
name: dm drogerie markt
description: dm active beauty Card
country: SK
domain: dm-drogeriemarkt.sk
category: pharmacy
barcode_type: ean13
brand:
  logo: siDm
  primary_color: "#FFD700"
  secondary_color: "#FFFFFF"
  text_color: "#000000"
apps:
  android:
    package: de.payback.client.android
    scheme: payback://
