id: edeka-de
name: "Edeka"
description: "Edeka Genuss+ Card"
country: DE
domain: "edeka.de"
category: groceries
barcode_type: ean13
brand:
  logo: siEdeka
  primary_color: "#FFD700"
  secondary_color: "#003399"
  text_color: "#003399"
