id: fnac-fr
name: "Fnac"
description: "Fnac+ Card"
country: FR
domain: "fnac.com"
category: electronics
barcode_type: ean13
brand:
  logo: siFnac
  primary_color: "#6F4E37"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
