id: hm-se
name: "H&M"
description: "H&M Member Card"
country: SE
domain: "hm.com"
category: fashion
barcode_type: ean13
brand:
  logo: siHandm
  primary_color: "#222222"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
# Official app store references.
apps:
  ios:
    store_id: "834465911"
  android:
    package: "com.hm.goe"
