id: jumbo-nl
name: Jumbo
description: Jumbo Extra's Card
country: NL
domain: jumbo.com
category: groceries
barcode_type: ean13
brand:
  primary_color: "#FFD700"
  secondary_color: "#000000"
  text_color: "#000000"
