id: mango
name: Mango
description: Mango Likes You Card
country: EU
domain: mango.com
category: fashion
barcode_type: qr
brand:
  primary_color: "#2C2C2C"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
