id: media-markt
name: MediaMarkt
description: MediaMarkt Club Card
country: EU
domain: mediamarkt.de
category: electronics
barcode_type: ean13
brand:
  logo: siMediamarkt
  primary_color: "#DF0000"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
