id: notino
name: "Notino"
description: "Notino Loyalty Card"
country: SK
domain: "notino.sk"
category: pharmacy
barcode_type: ean13
brand:
  primary_color: "#E20025"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
