id: payback-de
name: PAYBACK
description: PAYBACK Card
country: DE
domain: payback.de
category: other
barcode_type: ean13
brand:
  primary_color: "#003399"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
apps:
  android:
    package: de.payback.client.android
    scheme: payback://
