id: penny-cz
name: "Penny"
description: "Penny Card"
country: CZ
domain: "penny.cz"
category: groceries
barcode_type: ean13
brand:
  logo: siPenny
  primary_color: "#CD1719"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
# Official app store references.
apps:
  android:
    package: "cz.penny.app"
