id: pull-and-bear
name: "Pull & Bear"
description: "Pull & Bear Card"
country: EU
domain: "pullandbear.com"
category: fashion
barcode_type: qr
brand:
  primary_color: "#000000"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
# Official app store references.
apps:
  android:
    package: "com.pullandbear.pullandbear"
