id: reserved
name: "Reserved"
description: "Reserved Club Card"
country: SK
domain: "reserved.com"
category: fashion
barcode_type: ean13
brand:
  primary_color: "#000000"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
# Official app store references.
apps:
  android:
    package: "com.lpp.reserved"
