id: rewe-de
name: "REWE"
description: "REWE Bonus Card"
country: DE
domain: "rewe.de"
category: groceries
barcode_type: qr
brand:
  logo: siRewe
  primary_color: "#CC0000"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
