id: rossmann-pl
name: "Rossmann"
description: "Rossmann Club Card"
country: PL
domain: "rossmann.pl"
category: pharmacy
barcode_type: ean13
brand:
  logo: siRossmann
  primary_color: "#E30613"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
# Official app store references.
apps:
  android:
    package: "pl.rossmann.centauros"
