id: slovnaft
name: Slovnaft
description: Slovnaft Bonus Card
country: SK
domain: slovnaft.sk
category: petrol
barcode_type: ean13
brand:
  logo: siSlovnaft
  primary_color: "#E30613"
  secondary_color: "#FDB913"
  text_color: "#FFFFFF"
