id: spar-at
name: "SPAR"
description: "SPAR Friends Card"
country: AT
domain: "spar.at"
category: groceries
barcode_type: ean13
brand:
  logo: siSpar
  primary_color: "#009639"
  secondary_color: "#FFFFFF"
  text_color: "#FFFFFF"
