id: tchibo
name: "Tchibo"
description: "TchiboCard"
country: SK
domain: "tchibo.sk"
category: other
barcode_type: ean13
brand:
  primary_color: "#003D6B"
  secondary_color: "#E2001A"
  text_color: "#FFFFFF"
