id: tesco-hu
name: Tesco
description: Tesco ClubCard
country: HU
domain: tesco.hu
category: groceries
barcode_type: ean13
brand:
  logo: siTesco
  primary_color: "#00539F"
  secondary_color: "#EE1C2E"
  text_color: "#FFFFFF"
