id: tesco-gb
name: "Tesco"
description: "Tesco Clubcard"
country: GB
domain: "tesco.com"
category: groceries
barcode_type: ean13
brand:
  logo: siTesco
  primary_color: "#00539F"
  secondary_color: "#EE1C2E"
  text_color: "#FFFFFF"
